use_frameworks!

target 'QPFoundationExample' do
  platform :ios, '8.0'
  pod 'QPFoundation', :path => '../'
end

target 'QPGenerateNetworkingSources' do
  use_frameworks! :linkage => :static
  platform :osx, '10.8'
  pod 'QPFoundation', :path => '../'
end
